# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017-2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/kanas/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/kanas/proprietary/vendor/bin/at_distributor:system/vendor/bin/at_distributor \
    vendor/samsung/kanas/proprietary/vendor/bin/engpc:system/vendor/bin/engpc \
    vendor/samsung/kanas/proprietary/vendor/bin/ext_data.sh:system/vendor/bin/ext_data.sh \
    vendor/samsung/kanas/proprietary/vendor/bin/ext_kill.sh:system/vendor/bin/ext_kill.sh \
    vendor/samsung/kanas/proprietary/vendor/bin/ext_symlink.sh:system/vendor/bin/ext_symlink.sh \
    vendor/samsung/kanas/proprietary/vendor/bin/lpm:system/vendor/bin/lpm \
    vendor/samsung/kanas/proprietary/vendor/bin/macloader:system/vendor/bin/macloader \
    vendor/samsung/kanas/proprietary/vendor/bin/phoneserver:system/vendor/bin/phoneserver \
    vendor/samsung/kanas/proprietary/vendor/etc/AGPS_CA.pem:system/vendor/etc/AGPS_CA.pem \
    vendor/samsung/kanas/proprietary/vendor/etc/MSLConfig.txt:system/vendor/etc/MSLConfig.txt \
    vendor/samsung/kanas/proprietary/vendor/etc/license.key:system/vendor/etc/license.key \
    vendor/samsung/kanas/proprietary/vendor/etc/mrvl_agps_default.conf:system/vendor/etc/mrvl_agps_default.conf \
    vendor/samsung/kanas/proprietary/vendor/etc/mrvl_gps_platform.conf:system/vendor/etc/mrvl_gps_platform.conf \
    vendor/samsung/kanas/proprietary/vendor/etc/permissions/com.google.widevine.software.drm.xml:system/vendor/etc/permissions/com.google.widevine.software.drm.xml \
    vendor/samsung/kanas/proprietary/vendor/etc/plmn_delta.bin:system/vendor/etc/plmn_delta.bin \
    vendor/samsung/kanas/proprietary/vendor/etc/plmn_se13.bin:system/vendor/etc/plmn_se13.bin \
    vendor/samsung/kanas/proprietary/vendor/etc/pxa_testcfg.ini:system/vendor/etc/pxa_testcfg.ini \
    vendor/samsung/kanas/proprietary/vendor/etc/rom.bin:system/vendor/etc/rom.bin \
    vendor/samsung/kanas/proprietary/vendor/etc/rxn_config_data:system/vendor/etc/rxn_config_data \
    vendor/samsung/kanas/proprietary/vendor/etc/security.key:system/vendor/etc/security.key \
    vendor/samsung/kanas/proprietary/vendor/etc/wifi/bcmdhd_apsta.bin:system/vendor/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/kanas/proprietary/vendor/etc/wifi/bcmdhd_mfg.bin:system/vendor/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/kanas/proprietary/vendor/etc/wifi/bcmdhd_p2p.bin:system/vendor/etc/wifi/bcmdhd_p2p.bin \
    vendor/samsung/kanas/proprietary/vendor/etc/wifi/bcmdhd_sta.bin:system/vendor/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/kanas/proprietary/vendor/etc/wifi/nvram_mfg.txt:system/vendor/etc/wifi/nvram_mfg.txt \
    vendor/samsung/kanas/proprietary/vendor/etc/wifi/nvram_net.txt:system/vendor/etc/wifi/nvram_net.txt \
    vendor/samsung/kanas/proprietary/vendor/framework/com.google.widevine.software.drm.jar:system/vendor/framework/com.google.widevine.software.drm.jar \
    vendor/samsung/kanas/proprietary/vendor/lib/egl/libEGL_mali.so:system/vendor/lib/egl/libEGL_mali.so \
    vendor/samsung/kanas/proprietary/vendor/lib/egl/libGLESv1_CM_mali.so:system/vendor/lib/egl/libGLESv1_CM_mali.so \
    vendor/samsung/kanas/proprietary/vendor/lib/egl/libGLESv2_mali.so:system/vendor/lib/egl/libGLESv2_mali.so \
    vendor/samsung/kanas/proprietary/vendor/lib/hw/gps.vendor.sc8830.so:system/vendor/lib/hw/gps.vendor.sc8830.so \
    vendor/samsung/kanas/proprietary/vendor/lib/hw/gps.vendor.sc8830.so:system/vendor/lib/hw/gps.vendor.sc8830.so \
    vendor/samsung/kanas/proprietary/vendor/lib/libMali.so:system/vendor/lib/libMali.so \
    vendor/samsung/kanas/proprietary/vendor/lib/libQmageDecoder.so:system/vendor/lib/libQmageDecoder.so \
    vendor/samsung/kanas/proprietary/vendor/lib/libagps_hal.so:system/vendor/lib/libagps_hal.so \
    vendor/samsung/kanas/proprietary/vendor/lib/libatparser.so:system/vendor/lib/libatparser.so \
    vendor/samsung/kanas/proprietary/vendor/lib/libboost.so:system/vendor/lib/libboost.so \
    vendor/samsung/kanas/proprietary/vendor/lib/libfactoryutil.so:system/vendor/lib/libfactoryutil.so \
    vendor/samsung/kanas/proprietary/vendor/lib/libomission_avoidance.so:system/vendor/lib/libomission_avoidance.so \
    vendor/samsung/kanas/proprietary/vendor/lib/libomx_aacdec_sprd.so:system/vendor/lib/libomx_aacdec_sprd.so \
    vendor/samsung/kanas/proprietary/vendor/lib/libomx_avcdec_hw_sprd.so:system/vendor/lib/libomx_avcdec_hw_sprd.so \
    vendor/samsung/kanas/proprietary/vendor/lib/libomx_avcdec_sw_sprd.so:system/vendor/lib/libomx_avcdec_sw_sprd.so \
    vendor/samsung/kanas/proprietary/vendor/lib/libomx_avcenc_hw_sprd.so:system/vendor/lib/libomx_avcenc_hw_sprd.so \
    vendor/samsung/kanas/proprietary/vendor/lib/libomx_m4vh263dec_hw_sprd.so:system/vendor/lib/libomx_m4vh263dec_hw_sprd.so \
    vendor/samsung/kanas/proprietary/vendor/lib/libomx_m4vh263dec_sw_sprd.so:system/vendor/lib/libomx_m4vh263dec_sw_sprd.so \
    vendor/samsung/kanas/proprietary/vendor/lib/libomx_m4vh263enc_hw_sprd.so:system/vendor/lib/libomx_m4vh263enc_hw_sprd.so \
    vendor/samsung/kanas/proprietary/vendor/lib/libomx_mp3dec_sprd.so:system/vendor/lib/libomx_mp3dec_sprd.so \
    vendor/samsung/kanas/proprietary/vendor/lib/libomx_vpxdec_hw_sprd.so:system/vendor/lib/libomx_vpxdec_hw_sprd.so \
    vendor/samsung/kanas/proprietary/vendor/lib/libreference-ril_sp.so:system/vendor/lib/libreference-ril_sp.so \
    vendor/samsung/kanas/proprietary/vendor/lib/libsecnativefeature.so:system/vendor/lib/libsecnativefeature.so \
    vendor/samsung/kanas/proprietary/vendor/lib/libsprd_agps_agent.so:system/vendor/lib/libsprd_agps_agent.so \
    vendor/samsung/kanas/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/samsung/kanas/proprietary/vendor/media/Disconnected.qmg:system/vendor/media/Disconnected.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_batteryerror.qmg:system/vendor/media/battery_batteryerror.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_charging_10.qmg:system/vendor/media/battery_charging_10.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_charging_100.qmg:system/vendor/media/battery_charging_100.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_charging_15.qmg:system/vendor/media/battery_charging_15.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_charging_20.qmg:system/vendor/media/battery_charging_20.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_charging_25.qmg:system/vendor/media/battery_charging_25.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_charging_30.qmg:system/vendor/media/battery_charging_30.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_charging_35.qmg:system/vendor/media/battery_charging_35.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_charging_40.qmg:system/vendor/media/battery_charging_40.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_charging_45.qmg:system/vendor/media/battery_charging_45.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_charging_5.qmg:system/vendor/media/battery_charging_5.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_charging_50.qmg:system/vendor/media/battery_charging_50.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_charging_55.qmg:system/vendor/media/battery_charging_55.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_charging_60.qmg:system/vendor/media/battery_charging_60.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_charging_65.qmg:system/vendor/media/battery_charging_65.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_charging_70.qmg:system/vendor/media/battery_charging_70.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_charging_75.qmg:system/vendor/media/battery_charging_75.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_charging_80.qmg:system/vendor/media/battery_charging_80.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_charging_85.qmg:system/vendor/media/battery_charging_85.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_charging_90.qmg:system/vendor/media/battery_charging_90.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_charging_95.qmg:system/vendor/media/battery_charging_95.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/battery_error.qmg:system/vendor/media/battery_error.qmg \
    vendor/samsung/kanas/proprietary/vendor/media/chargingwarning.qmg:system/vendor/media/chargingwarning.qmg \
    vendor/samsung/kanas/proprietary/vendor/firmware/BCM4330B1_002.001.003.1025.1303.hcd:system/vendor/firmware/BCM4330B1_002.001.003.1025.1303.hcd \
    vendor/samsung/kanas/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/kanas/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/samsung/kanas/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so
